### ISSUE TITLE
Bitwise OR seems to be missing

### ISSUE THREAD

**Issue by elafargue** [google/kafel#14]
It looks like bitwise OR is defined in some parts of the lexer, but expression.c|h do not reference it. It looks like it's not possible to OR values, is that correct, and is this an oversight?

**Comment by happyCoder92** [comment]
Yep, it's currently not possible to bitwise OR values.
Actually I was thinking about adding some compile time arithmetic - should be fairly easy.
Will gladly accept pull requests ;)
