### ISSUE TITLE
Support SECCOMP_RET_KILL_PROCESS action

### ISSUE THREAD

**Issue by mejedi** [google/kafel#16]
Linux 4.14 introduced `SECCOMP_RET_KILL_PROCESS`. Former `SECCOMP_RET_KILL` is now know as `SECCOMP_RET_KILL_THREAD`.

The difference is quite profound, actually. Suggestion:

 * Extend the language, allowing `KILL THREAD` and `KILL PROCESS` (as two tokens) in addition to `KILL`;

 * `KILL` / `DENY` kills process on newer kernels, kills the calling thread on older ones.

It looks like returning `SECCOMP_RET_KILL_PROCESS (0x80000000)` on older kernels will be interpreted as `SECCOMP_RET_KILL (0)`:  unrecognized return values [are treated](https://elixir.bootlin.com/linux/v4.13.16/source/kernel/seccomp.c#L652) as `SECCOMP_RET_KILL`, high bit [is ignored](https://elixir.bootlin.com/linux/v4.13.16/source/kernel/seccomp.c#L201) when computing which action has the highest priority.

**Comment by happyCoder92** [comment]
Support for `SECCOMP_RET_KILL_PROCESS` was added.
I did not however change behavior of `KILL` and `DENY` as `SECCOMP_RET_KILL_THREAD` is a synonym of `SECCOMP_RET_KILL`.
