### ISSUE TITLE
Buildish time support?

### ISSUE THREAD

**Issue by nwmcsween** [google/kafel#17]
Hi I want to use kafel but don't want programs to be dependent on the library itself.

What I was thinking was to have a sort of `skafel("kafel string", &prog)` (static kafel) and a simple tool that wraps kafel to dump errors and update `prog` to contain the sock_filter, etc.

Issues and some solutions:
* How could it be used without scanning all files in a project for `skafel`?
  * pre-commit hook to mutate sock_fprog with a tool that can be used by itself (for manual updating).
* Could mutating sock_fprog have any side effects?

**Comment by happyCoder92** [comment]
Hi,

I added an option to dump_policy_bpf tool to output the bpf filter as array initializer using standard Linux macros.

Example:
mypolicy.kafel:
```
ALLOW { read }
DEFAULT DENY
```
mypolicy.c
```
#include <linux/filter.h>
#include <linux/seccomp.h>
#include <stddef.h>

int main(int argc, char* argv[]) {
  struct sock_filter policy[] = {
#include "mypolicy.kafel.h"
  };
  struct sock_fprog prog;
  prog.len = sizeof(policy)/sizeof(policy[0]);
  prog.filter = policy;
  ...
  return 0;
}
```
Makefile:
```
.SUFFIXES: .kafel
%.kafel.h: %.kafel
        $KAFEL_DIR/tools/dump_policy_bpf/dump_policy_bpf -c $< > $@
```
