### ISSUE TITLE
Missing syscalls from amd64

### ISSUE THREAD

**Issue by somethingnew2-0** [google/kafel#4]
Common syscalls like `send`, `sendfile`, `recv`, `stat`, `uname`, `waitpid`, and few others are missing from [syscalls/amd64_syscalls.c](https://github.com/google/kafel/blob/master/syscalls/amd64_syscalls.c)

Here's the list syscalls that are missing if you were to use the [default docker seccomp profile](https://github.com/docker/docker/blob/master/profiles/seccomp/default.json#L55-L357) using kafel.
```
chown32
fadvise64_64
fchown32
fcntl64
fstat64
fstatat64
fstatfs
fstatfs64
ftruncate64
getegid32
geteuid32
getgid32
getgroups32
getresgid32
getresuid32
getuid32
ipc
lchown32
_llseek
lstat
lstat64
mmap2
_newselect
recv
send
sendfile
sendfile64
setfsgid32
setfsuid32
setgid32
setgroups32
setregid32
setresgid32
setresuid32
setreuid32
setuid32
sigreturn
stat
stat64
statfs
statfs64
truncate64
ugetrlimit
uname
waitpid
```

As an aside, is there a reason these common syscalls are missing?

**Comment by happyCoder92** [comment]
Most of the syscalls from the list you provided are x86-only (`chown32`, `fchown32` and almost all `*32`).
Some syscalls are present under different name - `uname` as `newuname`.
It seems to be problematic to provide uniform naming for all syscalls.

**Comment by happyCoder92** [comment]
Closing as invalid as most of those are x86-only others are present in [syscalls/amd64_syscalls.c](https://github.com/google/kafel/blob/master/syscalls/amd64_syscalls.c), but under different names.
