### ISSUE TITLE
Support SECCOMP_RET_LOG action

### ISSUE THREAD

**Issue by nathancrandall** [google/kafel#8]
The latest version of seccomp now supports the `SECCOMP_RET_LOG` action (https://lkml.org/lkml/2017/8/11/16).  This is incredibly useful for debugging seccomp policies while in development.  It would be great if kafel could support a `LOG` action that corresponds to `SECCOMP_RET_LOG.`

**Comment by robertswiecki** [comment]
Hi, willing to craft a pull request? The original author of this library is no longer actively working on it. I'm maintaining it, but honestly, we have probably have the same knowledge on internals :). If not, I guess I can make a stab on it.

**Comment by nathancrandall** [comment]
Sure, I have a working change ready.  Surprisingly simple!

**Comment by nathancrandall** [comment]
Fixed with f664aca.
